# Generated by Django 3.2 on 2021-05-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='customer',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
