# Generated by Django 3.2 on 2021-05-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('UR', 'قيد المراجعة'), ('BA', 'تمت الموافة'), ('UP', 'قيد التحضر'), ('BS', 'تم الارسال'), ('DE', 'تم التوصيل')], default='UR', max_length=2),
        ),
    ]
