# Generated by Django 3.2 on 2021-05-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210502_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('NO', 'لم يم ارسالة بعد'), ('UR', 'قيد المراجعة'), ('BA', 'تمت الموافة'), ('UP', 'قيد التحضر'), ('BS', 'تم الارسال'), ('DE', 'تم التوصيل'), ('FH', 'تم إلغاء الطلب')], default='NO', max_length=2),
        ),
    ]
